services:
    mongodb:
        image: mongo:8.0.3
        ports:
            - '27017:27017'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: gJcXwU7QTb9e
        volumes:
            - mongodb_data:/data/db
        command: mongod --logpath /dev/null

    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        restart: always
        depends_on:
            - mongodb
        volumes:
            - .:/usr/src/app

volumes:
    mongodb_data:
